name: Modpack Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y zip jq curl
          echo -e "machine github.com\n  login ${GH_DEPLOY_KEY}" > ~/.netrc
          chmod +x ./scripts/buildPack.sh
          chmod +x ./scripts/deploy.sh
      - run: ./scripts/buildPack.sh
      - run: ./scripts/deploy.sh